import { Navbar } from '@/components/navbar';
import { Anton } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Admin',
  description: 'Generated by Next.js',
};

const anton = Anton({
  weight: '400',
  subsets: ['latin'],
});

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={anton.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
