import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function PublicLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <h1>Public Routes</h1>
                {children}
            </body>
        </html>
    )
}
